apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #IfNotPresent (default)
    ports:
    - containerPort: 80
      protocol: TCP