apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
  namespace: default
spec:
  selector:
    app: web-server
  ports:
    - protocol:
      port: 80
      name: default
  type: LoadBalancer