# A simple example of ClusterConfig object:
--- 
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    allowSSH: true
    sshPublicKeyPath: CMHKey
