# A simple example of ClusterConfig object:
--- 
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: <region>

nodeGroups:
  - name: node-group-1
    instanceType: t2.large
    desiredCapacity: 2
    allowSSH: true
    sshPublicKeyPath: <SSHKey>
