apiVersion: v1
kind: Pod
metadata:
  name: troubleshoot-util
  namespace: default
spec:
  containers:
  - name: troubleshoot-util
    image: patrickc3832/troubleshoot_util:awscli
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent