apiVersion: v1
kind: Pod
metadata:
  name: troubleshoot-util
  namespace: default
spec:
  containers:
  - name: troubleshoot-util
    image: public.ecr.aws/patrickc/troubleshoot-util
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
